---
- hosts: all

  become: yes

  tasks:

  - name: reboot
    reboot:

  - name: kernel
    shell: uname -r
    register: uname_result

  - name: kernel
    debug:
      msg: "kernel is {{ uname_result.stdout }}"
